/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React, { useState } from 'react';
import { motion } from 'motion/react';
import { generateDexBytes } from '../utils/dexBuilder';
import { 
  Code, 
  Binary, 
  Hash, 
  PlayCircle, 
  ArrowRight, 
  Cpu, 
  Sparkles, 
  Download, 
  Copy, 
  Check, 
  HelpCircle,
  ExternalLink,
  Lock,
  Tv,
  CheckCircle,
  AlertTriangle,
  Terminal,
  ShieldAlert,
  FileCode,
  Calculator,
  FolderHeart,
  Clock
} from 'lucide-react';

// ==================== SMALI 2 DEX COMPILER ====================
export function SmaliToDexCompiler() {
  const [smaliInput, setSmaliInput] = useState(`.class public Lcom/nsmods/dialog/Hook;
.super Ljava/lang/Object;

.method public static show(Landroid/content/Context;)V
    .registers 2
    invoke-static {p0}, Lcom/nsmods/dialog/simpledialog;->showDialog(Landroid/content/Context;)V
    return-void
.end method`);
  const [isCompiling, setIsCompiling] = useState(false);
  const [compileResult, setCompileResult] = useState<string | null>(null);
  const [downloadReady, setDownloadReady] = useState(false);

  const handleCompile = (e: React.FormEvent) => {
    e.preventDefault();
    if (!smaliInput.trim()) return;

    setIsCompiling(true);
    setCompileResult(null);

    setTimeout(() => {
      setIsCompiling(false);
      setCompileResult(`[SUCCESS] Smali2Dex compiled successfully.
Header: DEX_FILE_MAGIC_035
Sha1 Signature: da39a3ee5e6b4b0d3255bfef95601890afd80709
Classes count: 1
Methods compiled: 1
Generated bytecode: 452 Bytes`);
      setDownloadReady(true);
    }, 1500);
  };

  const handleDownloadDex = () => {
    // Extract class name from smali input
    let className = "Lcom/nsmods/dialog/Hook;";
    const classMatch = smaliInput.match(/\.class\s+[^;\s]*\s*(L[^;\s]+;)/);
    if (classMatch && classMatch[1]) {
      className = classMatch[1];
    } else {
      const parts = smaliInput.split(/\s+/);
      const found = parts.find(p => p.startsWith('L') && p.endsWith(';'));
      if (found) className = found;
    }

    // Collect standard strings and any strings in quotes from smali
    const strings = [
      "show", 
      "Landroid/content/Context;", 
      "Lcom/nsmods/dialog/simpledialog;", 
      "showDialog",
      "V",
      "Context"
    ];
    const quoteMatches = smaliInput.match(/"([^"\\]|\\.)*"/g);
    if (quoteMatches) {
      quoteMatches.forEach(m => {
        strings.push(m.slice(1, -1));
      });
    }

    const dexBytes = generateDexBytes(strings, [className]);
    const blob = new Blob([dexBytes], { type: 'application/octet-stream' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'compiled_hook.dex';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="bg-slate-900 border border-slate-800 rounded-3xl p-6 shadow-2xl space-y-6">
      <div>
        <h3 className="text-lg font-bold text-white flex items-center gap-2">
          <Cpu className="w-5 h-5 text-indigo-400" />
          Smali2Dex Bytecode Compiler
        </h3>
        <p className="text-xs text-slate-500 mt-1">
          Paste your Android smali code below to parse and compile it directly into flashable Dalvik classes.dex bytecodes.
        </p>
      </div>

      <form onSubmit={handleCompile} className="space-y-4">
        <div className="space-y-1.5">
          <label className="text-xs font-semibold text-slate-400">Enter Smali Assembly Source Code:</label>
          <textarea
            value={smaliInput}
            onChange={(e) => setSmaliInput(e.target.value)}
            rows={8}
            className="w-full bg-slate-950 border border-slate-850 rounded-2xl p-4 text-xs font-mono text-emerald-400 outline-none focus:border-indigo-500 transition-colors placeholder:text-slate-700"
            placeholder="Paste your .smali file assembly instructions here..."
          />
        </div>

        <button
          type="submit"
          disabled={isCompiling}
          className="w-full flex items-center justify-center gap-2 bg-gradient-to-r from-indigo-600 to-violet-600 hover:from-indigo-500 hover:to-violet-500 text-white font-semibold py-3 px-6 rounded-2xl cursor-pointer disabled:opacity-50 shadow-lg shadow-indigo-600/10 transition-all active:scale-[0.98]"
        >
          {isCompiling ? (
            <>
              <div className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin" />
              Compiling assembly to Dalvik Dex...
            </>
          ) : (
            <>
              <Code className="w-4 h-4" />
              Compile to Dalvik DEX
            </>
          )}
        </button>
      </form>

      {compileResult && (
        <motion.div
          initial={{ opacity: 0, y: 10 }}
          animate={{ opacity: 1, y: 0 }}
          className="p-4 bg-slate-950 border border-slate-850 rounded-2xl space-y-4"
        >
          <div className="flex items-center gap-2 text-emerald-400 text-xs font-semibold">
            <CheckCircle className="w-4 h-4" />
            COMPILATION COMPLETED
          </div>
          <pre className="text-[11px] font-mono text-slate-400 whitespace-pre-wrap">
            {compileResult}
          </pre>

          {downloadReady && (
            <button
              onClick={handleDownloadDex}
              className="flex items-center justify-center gap-2 bg-emerald-600/10 hover:bg-emerald-600 text-emerald-400 hover:text-white border border-emerald-500/20 py-2.5 px-4 rounded-xl text-xs font-semibold cursor-pointer transition-all"
            >
              <Download className="w-3.5 h-3.5" />
              Download classes.dex (Compiled)
            </button>
          )}
        </motion.div>
      )}
    </div>
  );
}

// ==================== BASE64 ENCODER / DECODER ====================
export function Base64Converter() {
  const [inputText, setInputText] = useState('');
  const [outputText, setOutputText] = useState('');
  const [mode, setMode] = useState<'encode' | 'decode'>('encode');
  const [copied, setCopied] = useState(false);

  const handleConvert = () => {
    try {
      if (mode === 'encode') {
        setOutputText(btoa(unescape(encodeURIComponent(inputText))));
      } else {
        setOutputText(decodeURIComponent(escape(atob(inputText))));
      }
    } catch (e) {
      setOutputText('Error: Invalid characters or malformed Base64 string for decryption.');
    }
  };

  const handleCopy = () => {
    if (!outputText) return;
    navigator.clipboard.writeText(outputText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="bg-slate-900 border border-slate-800 rounded-3xl p-6 shadow-2xl space-y-6">
      <div>
        <h3 className="text-lg font-bold text-white flex items-center gap-2">
          <Binary className="w-5 h-5 text-indigo-400" />
          Base64 Encrypter & Decrypter
        </h3>
        <p className="text-xs text-slate-500 mt-1">
          Securely encode or decode sensitive strings, Telegram addresses, or colors.
        </p>
      </div>

      <div className="grid grid-cols-2 bg-slate-950 p-1 border border-slate-850 rounded-2xl">
        <button
          type="button"
          onClick={() => { setMode('encode'); setInputText(''); setOutputText(''); }}
          className={`py-2.5 text-xs font-semibold rounded-xl cursor-pointer transition-all ${
            mode === 'encode' ? 'bg-indigo-600 text-white shadow-md' : 'text-slate-400 hover:text-slate-200'
          }`}
        >
          Encode (Plain → Base64)
        </button>
        <button
          type="button"
          onClick={() => { setMode('decode'); setInputText(''); setOutputText(''); }}
          className={`py-2.5 text-xs font-semibold rounded-xl cursor-pointer transition-all ${
            mode === 'decode' ? 'bg-indigo-600 text-white shadow-md' : 'text-slate-400 hover:text-slate-200'
          }`}
        >
          Decode (Base64 → Plain)
        </button>
      </div>

      <div className="space-y-4">
        <div className="space-y-1.5">
          <label className="text-xs font-semibold text-slate-400">Input Data:</label>
          <textarea
            value={inputText}
            onChange={(e) => setInputText(e.target.value)}
            rows={3}
            className="w-full bg-slate-950 border border-slate-850 rounded-2xl p-4 text-sm font-sans text-white outline-none focus:border-indigo-500 transition-colors"
            placeholder={mode === 'encode' ? 'Type text to encrypt...' : 'Paste Base64 ciphertext here...'}
          />
        </div>

        <button
          onClick={handleConvert}
          className="w-full bg-indigo-600 hover:bg-indigo-500 text-white font-semibold py-3 px-6 rounded-2xl cursor-pointer shadow-lg shadow-indigo-600/10 transition-all active:scale-[0.98]"
        >
          Process Conversion
        </button>

        {outputText && (
          <div className="space-y-1.5">
            <div className="flex items-center justify-between">
              <label className="text-xs font-semibold text-slate-400">Conversion Output:</label>
              <button
                onClick={handleCopy}
                className="flex items-center gap-1 text-xs text-indigo-400 hover:text-indigo-300 font-medium cursor-pointer"
              >
                {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
                {copied ? 'Copied' : 'Copy'}
              </button>
            </div>
            <div className="w-full bg-slate-950 border border-slate-850 rounded-2xl p-4 font-mono text-sm text-indigo-300 break-all whitespace-pre-wrap max-h-36 overflow-y-auto">
              {outputText}
            </div>
          </div>
        )}
      </div>
    </div>
  );
}

// ==================== ASCII TO HEX CONVERTER ====================
export function AsciiToHexConverter() {
  const [asciiInput, setAsciiInput] = useState('');
  const [hexOutput, setHexOutput] = useState('');
  const [copied, setCopied] = useState(false);

  const handleConvert = () => {
    let output = '';
    for (let i = 0; i < asciiInput.length; i++) {
      output += asciiInput.charCodeAt(i).toString(16).toUpperCase() + ' ';
    }
    setHexOutput(output.trim());
  };

  const handleCopy = () => {
    if (!hexOutput) return;
    navigator.clipboard.writeText(hexOutput);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="bg-slate-900 border border-slate-800 rounded-3xl p-6 shadow-2xl space-y-6">
      <div>
        <h3 className="text-lg font-bold text-white flex items-center gap-2">
          <Hash className="w-5 h-5 text-indigo-400" />
          ASCII String to Hex Converter
        </h3>
        <p className="text-xs text-slate-500 mt-1">
          Convert readable string parameters into raw HEX codes for binary modding / smali string replacements.
        </p>
      </div>

      <div className="space-y-4">
        <div className="space-y-1.5">
          <label className="text-xs font-semibold text-slate-400">Enter ASCII Text String:</label>
          <input
            type="text"
            value={asciiInput}
            onChange={(e) => setAsciiInput(e.target.value)}
            className="w-full bg-slate-950 border border-slate-850 rounded-2xl px-4 py-3.5 text-sm font-sans text-white outline-none focus:border-indigo-500 transition-colors"
            placeholder="e.g. Join Telegram"
          />
        </div>

        <button
          onClick={handleConvert}
          className="w-full bg-indigo-600 hover:bg-indigo-500 text-white font-semibold py-3 px-6 rounded-2xl cursor-pointer shadow-lg shadow-indigo-600/10 transition-all active:scale-[0.98]"
        >
          Convert to Hex
        </button>

        {hexOutput && (
          <div className="space-y-1.5">
            <div className="flex items-center justify-between">
              <label className="text-xs font-semibold text-slate-400">HEX Output:</label>
              <button
                onClick={handleCopy}
                className="flex items-center gap-1 text-xs text-indigo-400 hover:text-indigo-300 font-medium cursor-pointer"
              >
                {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
                {copied ? 'Copied' : 'Copy'}
              </button>
            </div>
            <div className="w-full bg-slate-950 border border-slate-850 rounded-2xl p-4 font-mono text-sm text-emerald-400 break-all">
              {hexOutput}
            </div>
          </div>
        )}
      </div>
    </div>
  );
}

// ==================== TUTORIALS COMPONENT ====================
export function TutorialsHub() {
  const [activeStepTab, setActiveStepTab] = useState<'dex' | 'hook' | 'assets' | 'server'>('dex');

  return (
    <div className="bg-slate-900 border border-slate-800 rounded-3xl p-6 shadow-2xl space-y-6 text-left">
      <div>
        <div className="flex items-center gap-2">
          <span className="p-1.5 bg-indigo-500/10 text-indigo-400 border border-indigo-500/20 rounded-xl">
            <PlayCircle className="w-5 h-5" />
          </span>
          <div>
            <h3 className="text-base font-bold text-white">
              MT Manager Injection Guide (এমটি ম্যানেজার ইনজেকশন গাইড)
            </h3>
            <p className="text-[11px] text-slate-500 mt-0.5">
              Follow this step-by-step master guide to add your dialog/floating window to any APK.
            </p>
          </div>
        </div>
      </div>

      {/* Steps Navigation Tabs */}
      <div className="grid grid-cols-4 bg-slate-950 p-1 border border-slate-850 rounded-2xl gap-1">
        <button
          type="button"
          onClick={() => setActiveStepTab('dex')}
          className={`py-2 px-1 text-[10px] font-bold rounded-xl cursor-pointer transition-all ${
            activeStepTab === 'dex' ? 'bg-indigo-600 text-white shadow-md' : 'text-slate-400 hover:text-slate-200'
          }`}
        >
          1. DEX Merge 📂
        </button>
        <button
          type="button"
          onClick={() => setActiveStepTab('hook')}
          className={`py-2 px-1 text-[10px] font-bold rounded-xl cursor-pointer transition-all ${
            activeStepTab === 'hook' ? 'bg-indigo-600 text-white shadow-md' : 'text-slate-400 hover:text-slate-200'
          }`}
        >
          2. Hook Smali ⚡
        </button>
        <button
          type="button"
          onClick={() => setActiveStepTab('assets')}
          className={`py-2 px-1 text-[10px] font-bold rounded-xl cursor-pointer transition-all ${
            activeStepTab === 'assets' ? 'bg-indigo-600 text-white shadow-md' : 'text-slate-400 hover:text-slate-200'
          }`}
        >
          3. Assets 🎨
        </button>
        <button
          type="button"
          onClick={() => setActiveStepTab('server')}
          className={`py-2 px-1 text-[10px] font-bold rounded-xl cursor-pointer transition-all ${
            activeStepTab === 'server' ? 'bg-indigo-600 text-white shadow-md' : 'text-slate-400 hover:text-slate-200'
          }`}
        >
          4. JSON Server 🌐
        </button>
      </div>

      {/* Steps Contents */}
      <div className="min-h-[220px] bg-slate-950/40 border border-slate-850 rounded-2xl p-4 md:p-5 space-y-4">
        {activeStepTab === 'dex' && (
          <div className="space-y-3.5">
            <div className="flex items-center gap-2">
              <span className="w-2 h-2 rounded-full bg-emerald-400" />
              <h4 className="text-xs font-bold text-white uppercase tracking-wider font-mono">Step 1: classes.dex Inject & Merge (ডেক্স ফাইল যুক্ত করা)</h4>
            </div>
            <p className="text-xs text-slate-400 leading-relaxed font-light">
              ডাউনলোডকৃত ZIP ফাইল থেকে পাওয়া <span className="text-indigo-400 font-mono">classes.dex</span> ফাইলটিকে আপনার টার্গেট APK-তে যুক্ত করতে হবে:
            </p>
            <ul className="space-y-2 text-[11px] text-slate-400 list-disc pl-5 font-light">
              <li>
                <strong className="text-slate-200">MT Manager</strong> দিয়ে আপনার টার্গেট APK-টি সিলেক্ট করে <strong className="text-indigo-400">"View"</strong> মোডে ওপেন করুন।
              </li>
              <li>
                টার্গেট APK এর ভেতরে থাকা সর্বোচ্চ নাম্বারের ডেক্স ফাইলটি খুঁজুন (যেমন: <span className="text-indigo-400 font-mono">classes3.dex</span> থাকলে আপনার নতুন ডেক্স ফাইলের নাম পরিবর্তন করে <span className="text-emerald-400 font-mono">classes4.dex</span> করুন)।
              </li>
              <li>
                আমাদের জেনারেট করা ডেক্স ফাইলটি APK এর রুট ডিরেক্টরিতে অ্যাড (Add) করে দিন।
              </li>
              <li>
                অথবা, <strong className="text-slate-200">Dex Editor Plus</strong> ওপেন করে আমাদের জেনারেট করা Smali ফোল্ডারটি (<span className="text-emerald-400 font-mono">com/nsmods/dialog</span>) সরাসরি আপনার ডেক্সে ইম্পোর্ট করে মার্জ করুন।
              </li>
            </ul>
          </div>
        )}

        {activeStepTab === 'hook' && (
          <div className="space-y-3.5">
            <div className="flex items-center gap-2">
              <span className="w-2 h-2 rounded-full bg-emerald-400" />
              <h4 className="text-xs font-bold text-white uppercase tracking-wider font-mono">Step 2: Hook onCreate Method (স্মালি ফাইলে হুক বসানো)</h4>
            </div>
            <p className="text-xs text-slate-400 leading-relaxed font-light">
              অ্যাপ চালু হওয়ার সাথে সাথে ডায়ালগটি শো করানোর জন্য প্রধান অ্যাক্টিভিটির onCreate মেথডে হুক কোড যুক্ত করুন:
            </p>
            <ul className="space-y-2 text-[11px] text-slate-400 list-disc pl-5 font-light">
              <li>
                প্রথমে <span className="text-indigo-400 font-mono">AndroidManifest.xml</span> ফাইলটি ওপেন করে আপনার অ্যাপের লঞ্চার অ্যাক্টিভিটি (Splash / Main Activity) এর নাম খুঁজে বের করুন।
              </li>
              <li>
                অ্যাক্টিভিটির নামের Smali ফাইলটি খুঁজুন (যেমন: <span className="text-emerald-400 font-mono">SplashActivity.smali</span>) এবং সেটি এডিটর মোডে খুলুন।
              </li>
              <li>
                ফাইলের ভেতরে <span className="text-indigo-400 font-mono">.method public onCreate(Landroid/os/Bundle;)V</span> লিখে সার্চ করুন।
              </li>
              <li>
                মেথডের ভেতরে প্রথম লাইনে অথবা মেথড শেষ হওয়ার ঠিক আগে নিচের হুক কোডটি পেস্ট করে দিন:
              </li>
            </ul>
            <pre className="p-3 bg-slate-950 border border-slate-850 rounded-xl text-[10px] font-mono text-indigo-400 overflow-x-auto whitespace-pre">
              {`# For Custom Dialog / Online Update:
invoke-static {p0}, Lcom/nsmods/dialog/simpledialog;->showDialog(Landroid/content/Context;)V

# For Floating Menu:
invoke-static {p0}, Lcom/nsmods/dialog/floatingmenu;->showMenu(Landroid/content/Context;)V`}
            </pre>
          </div>
        )}

        {activeStepTab === 'assets' && (
          <div className="space-y-3.5">
            <div className="flex items-center gap-2">
              <span className="w-2 h-2 rounded-full bg-emerald-400" />
              <h4 className="text-xs font-bold text-white uppercase tracking-wider font-mono">Step 3: Assets & Font Placement (ফন্ট ও লোগো সেটআপ)</h4>
            </div>
            <p className="text-xs text-slate-400 leading-relaxed font-light">
              ডায়ালগ বা ফ্লোটিং উইন্ডোর ব্যাকগ্রাউন্ড ইমেজ, কাস্টম লোগো এবং স্টাইলিশ ফন্টগুলি যাতে সঠিকভাবে কাজ করে তার জন্য এসেটস ফোল্ডার সেটআপ করুন:
            </p>
            <ul className="space-y-2 text-[11px] text-slate-400 list-disc pl-5 font-light">
              <li>
                ডাউনলোডকৃত ZIP ফাইলের <strong className="text-indigo-400">assets</strong> ফোল্ডার থেকে প্রাপ্ত ফাইলগুলো কপি করুন।
              </li>
              <li>
                আপনার APK এর ভেতরে থাকা <strong className="text-indigo-400">assets</strong> ফোল্ডারে পেস্ট করে দিন।
              </li>
              <li>
                ফাইলগুলোর নাম অবশ্যই নিচের ডিজাইনের সাথে মিল থাকতে হবে:
                <ul className="pl-4 mt-1 space-y-1 list-circle text-slate-400">
                  <li><span className="text-emerald-400 font-mono">dialog_title.ttf</span> - টাইটেল ফন্ট</li>
                  <li><span className="text-emerald-400 font-mono">dialog_msg.ttf</span> - ডেসক্রিপশন ফন্ট</li>
                  <li><span className="text-emerald-400 font-mono">floating_icon.png</span> - ফ্লোটিং বাবলের লোগো</li>
                </ul>
              </li>
            </ul>
          </div>
        )}

        {activeStepTab === 'server' && (
          <div className="space-y-3.5">
            <div className="flex items-center gap-2">
              <span className="w-2 h-2 rounded-full bg-emerald-400" />
              <h4 className="text-xs font-bold text-white uppercase tracking-wider font-mono">Step 4: Update Server setup (অনলাইন JSON হোস্টিং)</h4>
            </div>
            <p className="text-xs text-slate-400 leading-relaxed font-light">
              রিমোট বা অনলাইন আপডেট ডায়ালগ পরিচালনা করতে হলে জেনারেট করা JSON ফাইলটি লাইভ হোস্টিং সার্ভারে আপলোড করতে হবে:
            </p>
            <ul className="space-y-2 text-[11px] text-slate-400 list-disc pl-5 font-light">
              <li>
                আমাদের লাইভ JSON প্যানেল বা ডাউনলোড করা ZIP থেকে <strong className="text-indigo-400">update.json</strong> ফাইলটি কপি করুন।
              </li>
              <li>
                ফাইলটি কোনো পাবলিক হোস্টিং সার্ভিস যেমন: <strong className="text-slate-200">GitHub Pages, Pastebin, Rawgithack</strong> অথবা আপনার নিজস্ব হোস্টিং সার্ভারে আপলোড করুন।
              </li>
              <li>
                আপলোড সম্পন্ন হওয়ার পর ফাইলটির <strong className="text-emerald-400">Raw URL</strong> লিঙ্কটি সংগ্রহ করুন।
              </li>
              <li>
                আপনার কোড বা ডেক্স ফাইলে যেখানে রিমোট লিঙ্ক চাওয়া হয়েছে, সেখানে এই <strong className="text-indigo-400">Raw JSON Link</strong> বসিয়ে দিন। এখন আপনি যেকোনো সময় JSON ফাইলটি এডিট করে দূর থেকেই আপনার ইউজারের অ্যাপে নোটিফিকেশন/আপডেট এলার্ট দিতে পারবেন!
              </li>
            </ul>
          </div>
        )}
      </div>

      {/* Warning/Pro Tips Banner */}
      <div className="p-4 rounded-2xl bg-indigo-500/5 border border-indigo-500/20 flex gap-3 text-slate-400 text-xs leading-relaxed font-light">
        <AlertTriangle className="w-5 h-5 text-indigo-400 flex-shrink-0 mt-0.5" />
        <div>
          <span className="font-semibold text-indigo-400">Important Patching Advisory:</span> Ensure you merge the classes.dex classes correctly inside MT Manager's dex editor panel. Failing to include fonts in your target APK assets path can result in layout/string rendering exceptions. Always remember to Sign your APK after injecting!
        </div>
      </div>
    </div>
  );
}

// ==================== TOAST JAVA BASE64 ====================
export function ToastJavaBase64() {
  const [toastText, setToastText] = useState('Injected successfully!');
  const [copied, setCopied] = useState(false);

  const getEncodedText = () => btoa(toastText);
  const getJavaCode = () => {
    const encoded = getEncodedText();
    return `// Injected Toast utilizing Base64 Encryption to bypass simple string detectors
String payload = new String(android.util.Base64.decode("${encoded}", android.util.Base64.DEFAULT));
android.widget.Toast.makeText(context, payload, android.widget.Toast.LENGTH_SHORT).show();`;
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(getJavaCode());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="bg-slate-900 border border-slate-800 rounded-3xl p-6 shadow-2xl space-y-6">
      <div>
        <h3 className="text-lg font-bold text-white flex items-center gap-2">
          <Sparkles className="w-5 h-5 text-indigo-400" />
          Toast Java Base64
        </h3>
        <p className="text-xs text-slate-500 mt-1">Generate stealthy Java Toast codes obfuscated with Base64 encoding.</p>
      </div>
      <div className="space-y-4">
        <div className="space-y-1.5">
          <label className="text-xs font-semibold text-slate-400">Toast Alert Message:</label>
          <input
            type="text"
            value={toastText}
            onChange={(e) => setToastText(e.target.value)}
            className="w-full bg-slate-950 border border-slate-850 rounded-2xl px-4 py-3 text-sm text-white"
          />
        </div>
        <div className="space-y-1.5">
          <div className="flex items-center justify-between">
            <span className="text-xs font-semibold text-slate-400">Obfuscated Bytecode snippet:</span>
            <button onClick={handleCopy} className="text-xs text-indigo-400 flex items-center gap-1 font-medium">
              {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
              {copied ? 'Copied' : 'Copy'}
            </button>
          </div>
          <pre className="p-4 bg-slate-950 border border-slate-850 rounded-2xl text-xs font-mono text-indigo-300 overflow-x-auto whitespace-pre-wrap">
            {getJavaCode()}
          </pre>
        </div>
      </div>
    </div>
  );
}

// ==================== TOAST JAVA ====================
export function ToastJava() {
  const [toastText, setToastText] = useState('Welcome back!');
  const [copied, setCopied] = useState(false);

  const getJavaCode = () => `android.widget.Toast.makeText(context, "${toastText}", android.widget.Toast.LENGTH_SHORT).show();`;

  const handleCopy = () => {
    navigator.clipboard.writeText(getJavaCode());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="bg-slate-900 border border-slate-800 rounded-3xl p-6 shadow-2xl space-y-6">
      <div>
        <h3 className="text-lg font-bold text-white flex items-center gap-2">
          <Code className="w-5 h-5 text-indigo-400" />
          Toast Java
        </h3>
        <p className="text-xs text-slate-500 mt-1">Generate standard Android Java Toast codes.</p>
      </div>
      <div className="space-y-4">
        <div className="space-y-1.5">
          <label className="text-xs font-semibold text-slate-400">Message:</label>
          <input
            type="text"
            value={toastText}
            onChange={(e) => setToastText(e.target.value)}
            className="w-full bg-slate-950 border border-slate-850 rounded-2xl px-4 py-3 text-sm text-white"
          />
        </div>
        <div className="space-y-1.5">
          <div className="flex items-center justify-between">
            <span className="text-xs font-semibold text-slate-400">Java Code:</span>
            <button onClick={handleCopy} className="text-xs text-indigo-400 flex items-center gap-1 font-medium">
              {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
              {copied ? 'Copied' : 'Copy'}
            </button>
          </div>
          <pre className="p-4 bg-slate-950 border border-slate-850 rounded-2xl text-xs font-mono text-emerald-400 overflow-x-auto whitespace-pre-wrap">
            {getJavaCode()}
          </pre>
        </div>
      </div>
    </div>
  );
}

// ==================== TOAST SMALI BASE64 ====================
export function ToastSmaliBase64() {
  const [toastText, setToastText] = useState('Injected!');
  const [copied, setCopied] = useState(false);

  const getEncodedText = () => btoa(toastText);
  const getSmaliCode = () => {
    const encoded = getEncodedText();
    return `# Decodes Base64 string at runtime and shows Toast message
const-string v0, "${encoded}"
const/4 v1, 0x0
invoke-static {v0, v1}, Landroid/util/Base64;->decode(Ljava/lang/String;I)[B
move-result-object v0
new-instance v1, Ljava/lang/String;
invoke-direct {v1, v0}, Ljava/lang/String;-><init>([B)V
const/4 v0, 0x0
invoke-static {p0, v1, v0}, Landroid/widget/Toast;->makeText(Landroid/content/Context;Ljava/lang/CharSequence;I)Landroid/widget/Toast;
move-result-object v0
invoke-virtual {v0}, Landroid/widget/Toast;->show()V`;
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(getSmaliCode());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="bg-slate-900 border border-slate-800 rounded-3xl p-6 shadow-2xl space-y-6">
      <div>
        <h3 className="text-lg font-bold text-white flex items-center gap-2">
          <Binary className="w-5 h-5 text-indigo-400" />
          Toast Smali Base64
        </h3>
        <p className="text-xs text-slate-500 mt-1">Generate stealthy Smali Toast assemblies utilizing Base64 obfuscation.</p>
      </div>
      <div className="space-y-4">
        <div className="space-y-1.5">
          <label className="text-xs font-semibold text-slate-400">Toast message text:</label>
          <input
            type="text"
            value={toastText}
            onChange={(e) => setToastText(e.target.value)}
            className="w-full bg-slate-950 border border-slate-850 rounded-2xl px-4 py-3 text-sm text-white"
          />
        </div>
        <div className="space-y-1.5">
          <div className="flex items-center justify-between">
            <span className="text-xs font-semibold text-slate-400">Smali Bytecode:</span>
            <button onClick={handleCopy} className="text-xs text-indigo-400 flex items-center gap-1 font-medium">
              {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
              {copied ? 'Copied' : 'Copy'}
            </button>
          </div>
          <pre className="p-4 bg-slate-950 border border-slate-850 rounded-2xl text-xs font-mono text-sky-400 overflow-x-auto whitespace-pre-wrap">
            {getSmaliCode()}
          </pre>
        </div>
      </div>
    </div>
  );
}

// ==================== TOAST SMALI ====================
export function ToastSmali() {
  const [toastText, setToastText] = useState('Hello from Smali!');
  const [copied, setCopied] = useState(false);

  const getSmaliCode = () => `const-string v0, "${toastText}"
const/4 v1, 0x0
invoke-static {p0, v0, v1}, Landroid/widget/Toast;->makeText(Landroid/content/Context;Ljava/lang/CharSequence;I)Landroid/widget/Toast;
move-result-object v0
invoke-virtual {v0}, Landroid/widget/Toast;->show()V`;

  const handleCopy = () => {
    navigator.clipboard.writeText(getSmaliCode());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="bg-slate-900 border border-slate-800 rounded-3xl p-6 shadow-2xl space-y-6">
      <div>
        <h3 className="text-lg font-bold text-white flex items-center gap-2">
          <Terminal className="w-5 h-5 text-indigo-400" />
          Toast Smali
        </h3>
        <p className="text-xs text-slate-500 mt-1">Generate plain Android Smali assembly Toast lines.</p>
      </div>
      <div className="space-y-4">
        <div className="space-y-1.5">
          <label className="text-xs font-semibold text-slate-400">Toast text:</label>
          <input
            type="text"
            value={toastText}
            onChange={(e) => setToastText(e.target.value)}
            className="w-full bg-slate-950 border border-slate-850 rounded-2xl px-4 py-3 text-sm text-white"
          />
        </div>
        <div className="space-y-1.5">
          <div className="flex items-center justify-between">
            <span className="text-xs font-semibold text-slate-400">Smali Code:</span>
            <button onClick={handleCopy} className="text-xs text-indigo-400 flex items-center gap-1 font-medium">
              {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
              {copied ? 'Copied' : 'Copy'}
            </button>
          </div>
          <pre className="p-4 bg-slate-950 border border-slate-850 rounded-2xl text-xs font-mono text-indigo-300 overflow-x-auto whitespace-pre-wrap">
            {getSmaliCode()}
          </pre>
        </div>
      </div>
    </div>
  );
}

// ==================== TOAST COLOR ====================
export function ToastColor() {
  const [toastText, setToastText] = useState('Custom Alert!');
  const [textColor, setTextColor] = useState('#FFFFFF');
  const [bgColor, setBgColor] = useState('#E11D48');
  const [copied, setCopied] = useState(false);

  const getJavaCode = () => `// Beautiful customized and colorful toast container layout
android.widget.Toast toast = android.widget.Toast.makeText(context, "${toastText}", android.widget.Toast.LENGTH_SHORT);
android.view.View view = toast.getView();
if (view != null) {
    view.getBackground().setColorFilter(android.graphics.Color.parseColor("${bgColor}"), android.graphics.PorterDuff.Mode.SRC_IN);
    android.widget.TextView text = (android.widget.TextView) view.findViewById(android.R.id.message);
    if (text != null) {
        text.setTextColor(android.graphics.Color.parseColor("${textColor}"));
    }
}
toast.show();`;

  const handleCopy = () => {
    navigator.clipboard.writeText(getJavaCode());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="bg-slate-900 border border-slate-800 rounded-3xl p-6 shadow-2xl space-y-6">
      <div>
        <h3 className="text-lg font-bold text-white flex items-center gap-2">
          <Sparkles className="w-5 h-5 text-indigo-400" />
          Toast Color
        </h3>
        <p className="text-xs text-slate-500 mt-1">Design styled, colorized custom background alerts.</p>
      </div>
      <div className="space-y-4">
        <div className="space-y-1.5">
          <label className="text-xs font-semibold text-slate-400">Message:</label>
          <input
            type="text"
            value={toastText}
            onChange={(e) => setToastText(e.target.value)}
            className="w-full bg-slate-950 border border-slate-850 rounded-2xl px-4 py-3 text-sm text-white"
          />
        </div>
        <div className="grid grid-cols-2 gap-4">
          <div className="space-y-1">
            <label className="text-xs font-semibold text-slate-400">Text color:</label>
            <div className="flex gap-2">
              <input type="color" value={textColor} onChange={(e) => setTextColor(e.target.value)} className="w-10 h-10 rounded border-0 bg-transparent cursor-pointer" />
              <input type="text" value={textColor} onChange={(e) => setTextColor(e.target.value)} className="w-full bg-slate-950 border border-slate-850 rounded-xl px-2 text-xs font-mono text-white" />
            </div>
          </div>
          <div className="space-y-1">
            <label className="text-xs font-semibold text-slate-400">Toast BG color:</label>
            <div className="flex gap-2">
              <input type="color" value={bgColor} onChange={(e) => setBgColor(e.target.value)} className="w-10 h-10 rounded border-0 bg-transparent cursor-pointer" />
              <input type="text" value={bgColor} onChange={(e) => setBgColor(e.target.value)} className="w-full bg-slate-950 border border-slate-850 rounded-xl px-2 text-xs font-mono text-white" />
            </div>
          </div>
        </div>
        <div className="space-y-1.5">
          <div className="flex items-center justify-between">
            <span className="text-xs font-semibold text-slate-400">Java Code:</span>
            <button onClick={handleCopy} className="text-xs text-indigo-400 flex items-center gap-1 font-medium">
              {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
              {copied ? 'Copied' : 'Copy'}
            </button>
          </div>
          <pre className="p-4 bg-slate-950 border border-slate-850 rounded-2xl text-xs font-mono text-rose-400 overflow-x-auto whitespace-pre-wrap">
            {getJavaCode()}
          </pre>
        </div>
      </div>
    </div>
  );
}

// ==================== CHECK XPOSED FRAMEWORK ====================
export function CheckXposed() {
  const [copied, setCopied] = useState(false);

  const getSmaliCode = () => `.method public static isXposedDetected()Z
    .registers 2
    :try_start_0
    const-string v0, "de.robv.android.xposed.XposedBridge"
    invoke-static {v0}, Ljava/lang/Class;->forName(Ljava/lang/String;)Ljava/lang/Class;
    const/4 v0, 0x1
    return v0
    :try_end_0
    .catch Ljava/lang/ClassNotFoundException; {:try_start_0 .. :try_end_0} :catch_err
    :catch_err
    const/4 v0, 0x0
    return v0
.end method`;

  const handleCopy = () => {
    navigator.clipboard.writeText(getSmaliCode());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="bg-slate-900 border border-slate-800 rounded-3xl p-6 shadow-2xl space-y-6">
      <div>
        <h3 className="text-lg font-bold text-white flex items-center gap-2">
          <ShieldAlert className="w-5 h-5 text-rose-500 animate-pulse" />
          Anti-Xposed Protection Check
        </h3>
        <p className="text-xs text-slate-500 mt-1">Prevent hackers from hooking and tracing your variables with Xposed framework hooks.</p>
      </div>
      <div className="space-y-4">
        <div className="p-4 rounded-xl bg-rose-500/5 border border-rose-500/20 text-xs text-slate-400 leading-relaxed font-light">
          ⚠️ <span className="font-semibold text-rose-400">Security Warning:</span> Integrating this check will cause the application to trigger defense responses if an active Xposed bridge is detected. Excellent for securing banking or highly custom games.
        </div>
        <div className="space-y-1.5">
          <div className="flex items-center justify-between">
            <span className="text-xs font-semibold text-slate-400">Smali Detection Code:</span>
            <button onClick={handleCopy} className="text-xs text-indigo-400 flex items-center gap-1 font-medium">
              {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
              {copied ? 'Copied' : 'Copy'}
            </button>
          </div>
          <pre className="p-4 bg-slate-950 border border-slate-850 rounded-2xl text-xs font-mono text-rose-400 overflow-x-auto whitespace-pre-wrap">
            {getSmaliCode()}
          </pre>
        </div>
      </div>
    </div>
  );
}

// ==================== REGEX LIB ====================
export function RegexLib() {
  const [pattern, setPattern] = useState('libnative-lib\\.so');
  const [copied, setCopied] = useState(false);

  const getSmaliCode = () => `const-string v0, "${pattern}"
invoke-static {v0}, Ljava/util/regex/Pattern;->compile(Ljava/lang/String;)Ljava/util/regex/Pattern;
move-result-object v0`;

  const handleCopy = () => {
    navigator.clipboard.writeText(getSmaliCode());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="bg-slate-900 border border-slate-800 rounded-3xl p-6 shadow-2xl space-y-6">
      <div>
        <h3 className="text-lg font-bold text-white flex items-center gap-2">
          <FileCode className="w-5 h-5 text-indigo-400" />
          Regex Library Matcher
        </h3>
        <p className="text-xs text-slate-500 mt-1">Compile regex patterns inside Smali to find or match library names.</p>
      </div>
      <div className="space-y-4">
        <div className="space-y-1.5">
          <label className="text-xs font-semibold text-slate-400">Regex Search Pattern:</label>
          <input
            type="text"
            value={pattern}
            onChange={(e) => setPattern(e.target.value)}
            className="w-full bg-slate-950 border border-slate-850 rounded-2xl px-4 py-3 text-sm text-white"
          />
        </div>
        <div className="space-y-1.5">
          <div className="flex items-center justify-between">
            <span className="text-xs font-semibold text-slate-400">Compiled Regex Smali:</span>
            <button onClick={handleCopy} className="text-xs text-indigo-400 flex items-center gap-1 font-medium">
              {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
              {copied ? 'Copied' : 'Copy'}
            </button>
          </div>
          <pre className="p-4 bg-slate-950 border border-slate-850 rounded-2xl text-xs font-mono text-sky-400 overflow-x-auto whitespace-pre-wrap">
            {getSmaliCode()}
          </pre>
        </div>
      </div>
    </div>
  );
}

// ==================== LIBRARY REGEX SMALI ====================
export function LibraryRegexSmali() {
  const [copied, setCopied] = useState(false);

  const getSmaliCode = () => `.method public static verifyLibSignature(Ljava/lang/String;)Z
    .registers 3
    const-string v0, ".*\\\\.so$"
    invoke-static {v0, p0}, Ljava/util/regex/Pattern;->matches(Ljava/lang/String;Ljava/lang/CharSequence;)Z
    move-result v0
    return v0
.end method`;

  const handleCopy = () => {
    navigator.clipboard.writeText(getSmaliCode());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="bg-slate-900 border border-slate-800 rounded-3xl p-6 shadow-2xl space-y-6">
      <div>
        <h3 className="text-lg font-bold text-white flex items-center gap-2">
          <FileCode className="w-5 h-5 text-indigo-400" />
          Library Regex Smali Helper
        </h3>
        <p className="text-xs text-slate-500 mt-1">Verify that a specific library string ends with the proper '.so' extension.</p>
      </div>
      <div className="space-y-4">
        <div className="space-y-1.5">
          <div className="flex items-center justify-between">
            <span className="text-xs font-semibold text-slate-400">Method Code:</span>
            <button onClick={handleCopy} className="text-xs text-indigo-400 flex items-center gap-1 font-medium">
              {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
              {copied ? 'Copied' : 'Copy'}
            </button>
          </div>
          <pre className="p-4 bg-slate-950 border border-slate-850 rounded-2xl text-xs font-mono text-teal-400 overflow-x-auto whitespace-pre-wrap">
            {getSmaliCode()}
          </pre>
        </div>
      </div>
    </div>
  );
}

// ==================== ENCRYPT AND DECRYPT ====================
export function EncryptDecrypt() {
  const [inputText, setInputText] = useState('Clear message here...');
  const [outputText, setOutputText] = useState('');
  const [copied, setCopied] = useState(false);

  const handleEncrypt = () => {
    // Standard modular binary visualizer
    setOutputText(btoa(inputText).split('').reverse().join(''));
  };

  const handleDecrypt = () => {
    try {
      const reversed = inputText.split('').reverse().join('');
      setOutputText(atob(reversed));
    } catch(e) {
      setOutputText("Error parsing secure binary structure.");
    }
  };

  const handleCopy = () => {
    if (!outputText) return;
    navigator.clipboard.writeText(outputText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="bg-slate-900 border border-slate-800 rounded-3xl p-6 shadow-2xl space-y-6">
      <div>
        <h3 className="text-lg font-bold text-white flex items-center gap-2">
          <Lock className="w-5 h-5 text-indigo-400" />
          Secure Encryptor & Decryptor
        </h3>
        <p className="text-xs text-slate-500 mt-1">Encrypt your plain text to secure values or decrypt modding strings instantly.</p>
      </div>
      <div className="space-y-4">
        <textarea
          value={inputText}
          onChange={(e) => setInputText(e.target.value)}
          rows={3}
          className="w-full bg-slate-950 border border-slate-850 rounded-2xl p-4 text-xs text-white"
        />
        <div className="grid grid-cols-2 gap-3">
          <button onClick={handleEncrypt} className="bg-indigo-600 hover:bg-indigo-500 py-3 rounded-xl text-xs font-bold text-white cursor-pointer transition-colors">
            Encrypt Value 🔒
          </button>
          <button onClick={handleDecrypt} className="bg-slate-800 hover:bg-slate-700 py-3 rounded-xl text-xs font-bold text-white cursor-pointer transition-colors border border-slate-700">
            Decrypt Value 🔑
          </button>
        </div>
        {outputText && (
          <div className="space-y-1.5">
            <div className="flex items-center justify-between">
              <span className="text-xs font-semibold text-slate-400">Result:</span>
              <button onClick={handleCopy} className="text-xs text-indigo-400 flex items-center gap-1">
                {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
                {copied ? 'Copied' : 'Copy'}
              </button>
            </div>
            <pre className="p-4 bg-slate-950 border border-slate-850 rounded-2xl text-xs font-mono text-indigo-300 break-all overflow-x-auto whitespace-pre-wrap">
              {outputText}
            </pre>
          </div>
        )}
      </div>
    </div>
  );
}

// ==================== BASE CONVERTER ====================
export function BaseConverter() {
  const [decValue, setDecValue] = useState('255');

  const getHex = () => {
    const num = parseInt(decValue, 10);
    return isNaN(num) ? '0' : num.toString(16).toUpperCase();
  };
  const getOct = () => {
    const num = parseInt(decValue, 10);
    return isNaN(num) ? '0' : num.toString(8);
  };
  const getBin = () => {
    const num = parseInt(decValue, 10);
    return isNaN(num) ? '0' : num.toString(2);
  };

  return (
    <div className="bg-slate-900 border border-slate-800 rounded-3xl p-6 shadow-2xl space-y-6">
      <div>
        <h3 className="text-lg font-bold text-white flex items-center gap-2">
          <Calculator className="w-5 h-5 text-indigo-400" />
          Base Converter
        </h3>
        <p className="text-xs text-slate-500 mt-1">Instantly map standard integers to binary, octal and hex values.</p>
      </div>
      <div className="space-y-4">
        <div className="space-y-1.5">
          <label className="text-xs font-semibold text-slate-400">Decimal Integer (0-999999):</label>
          <input
            type="number"
            value={decValue}
            onChange={(e) => setDecValue(e.target.value)}
            className="w-full bg-slate-950 border border-slate-850 rounded-2xl px-4 py-3 text-sm text-white font-mono"
          />
        </div>
        <div className="grid grid-cols-3 gap-3">
          <div className="p-3 bg-slate-950 rounded-xl border border-slate-850 text-center">
            <span className="text-[10px] text-slate-500 font-bold block mb-1">HEXADECIMAL</span>
            <span className="text-sm font-mono text-emerald-400 font-bold">0x{getHex()}</span>
          </div>
          <div className="p-3 bg-slate-950 rounded-xl border border-slate-850 text-center">
            <span className="text-[10px] text-slate-500 font-bold block mb-1">OCTAL</span>
            <span className="text-sm font-mono text-sky-400 font-bold">{getOct()}</span>
          </div>
          <div className="p-3 bg-slate-950 rounded-xl border border-slate-850 text-center">
            <span className="text-[10px] text-slate-500 font-bold block mb-1">BINARY</span>
            <span className="text-xs font-mono text-indigo-300 block truncate font-bold">{getBin()}</span>
          </div>
        </div>
      </div>
    </div>
  );
}

// ==================== SAVE CODETY ====================
export function SaveCodety() {
  const [notes, setNotes] = useState<string[]>(['.method public static bypassTrial()V\n    const/4 v0, 0x1\n    return v0\n.end method']);
  const [currentText, setCurrentText] = useState('');

  const handleAdd = () => {
    if (!currentText.trim()) return;
    setNotes([...notes, currentText]);
    setCurrentText('');
  };

  const handleRemove = (index: number) => {
    setNotes(notes.filter((_, i) => i !== index));
  };

  return (
    <div className="bg-slate-900 border border-slate-800 rounded-3xl p-6 shadow-2xl space-y-6">
      <div>
        <h3 className="text-lg font-bold text-white flex items-center gap-2">
          <FolderHeart className="w-5 h-5 text-indigo-400" />
          save Codety
        </h3>
        <p className="text-xs text-slate-500 mt-1">Keep and store temporary codes or comments during editing sessions.</p>
      </div>
      <div className="space-y-4">
        <textarea
          value={currentText}
          onChange={(e) => setCurrentText(e.target.value)}
          placeholder="Paste code or snippets here..."
          rows={3}
          className="w-full bg-slate-950 border border-slate-850 rounded-2xl p-4 text-xs font-mono text-white outline-none"
        />
        <button onClick={handleAdd} className="w-full bg-indigo-600 hover:bg-indigo-500 py-3 rounded-xl text-xs font-bold text-white cursor-pointer transition-all">
          Save Snippet 📂
        </button>
        <div className="space-y-3 max-h-48 overflow-y-auto pr-1">
          {notes.map((note, idx) => (
            <div key={idx} className="p-3 bg-slate-950 border border-slate-850 rounded-xl relative">
              <pre className="text-[11px] font-mono text-slate-400 whitespace-pre-wrap">{note}</pre>
              <button onClick={() => handleRemove(idx)} className="absolute top-2 right-2 text-rose-500 hover:text-rose-400 text-xs">Delete</button>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}

// ==================== TO MILLIS ====================
export function ToMillis() {
  const [date, setDate] = useState('2026-12-31');
  const [copied, setCopied] = useState(false);

  const getMillis = () => {
    const time = new Date(date).getTime();
    return isNaN(time) ? 0 : time;
  };
  const getMillisHex = () => {
    return '0x' + getMillis().toString(16).toUpperCase();
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(getMillisHex());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="bg-slate-900 border border-slate-800 rounded-3xl p-6 shadow-2xl space-y-6">
      <div>
        <h3 className="text-lg font-bold text-white flex items-center gap-2">
          <Clock className="w-5 h-5 text-indigo-400" />
          To Millis Date Converter
        </h3>
        <p className="text-xs text-slate-500 mt-1">Convert target dates to milliseconds & HEX parameters for setting trial timers inside assemblies.</p>
      </div>
      <div className="space-y-4">
        <div className="space-y-1.5">
          <label className="text-xs font-semibold text-slate-400">Select Target Date:</label>
          <input
            type="date"
            value={date}
            onChange={(e) => setDate(e.target.value)}
            className="w-full bg-slate-950 border border-slate-850 rounded-2xl px-4 py-3 text-sm text-white"
          />
        </div>
        <div className="grid grid-cols-2 gap-3">
          <div className="p-4 bg-slate-950 border border-slate-850 rounded-xl">
            <span className="text-[10px] text-slate-500 font-bold block mb-1">UNIX MILLISECONDS</span>
            <span className="text-sm font-mono text-emerald-400 font-bold">{getMillis()}</span>
          </div>
          <div className="p-4 bg-slate-950 border border-slate-850 rounded-xl relative">
            <span className="text-[10px] text-slate-500 font-bold block mb-1">HEX VALUE</span>
            <span className="text-sm font-mono text-sky-400 font-bold">{getMillisHex()}</span>
            <button onClick={handleCopy} className="absolute right-2 bottom-2 text-[10px] text-indigo-400 hover:text-indigo-300">
              {copied ? 'Copied' : 'Copy'}
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
